import { Round1QuestionsType } from "../round_one.types";

export const round1_questions: Round1QuestionsType[] = [
  {
    _id: "css-001",
    question: "What does CSS stand for?",
    options: [
      "Cascading Style Sheets",
      "Creative Style System",
      "Computer Style Syntax",
      "Colorful Style Sheets",
    ],
    correctOption: 0,
    difficulty: "easy",
    marks: 1,
    isActive: true,
    userAnswer: null,
    isCorrect: null,
    isVisited: false,
  },
  {
    _id: "html-001",
    question: "Which HTML tag is used to include JavaScript?",
    options: ["<js>", "<javascript>", "<script>", "<code>"],
    correctOption: 2,
    difficulty: "easy",
    marks: 1,
    isActive: true,
    userAnswer: null,
    isCorrect: null,
    isVisited: false,
  },
  {
    _id: "http-001",
    question: "Which HTTP method is idempotent?",
    options: ["POST", "PATCH", "GET", "CONNECT"],
    correctOption: 2,
    difficulty: "easy",
    marks: 1,
    isActive: true,
    userAnswer: null,
    isCorrect: null,
    isVisited: false,
  },
  {
    _id: "sql-001",
    question: "What does SQL stand for?",
    options: [
      "Structured Query Language",
      "Sequential Query Logic",
      "Simple Query Language",
      "Standard Query List",
    ],
    correctOption: 0,
    difficulty: "easy",
    marks: 1,
    isActive: true,
    userAnswer: null,
    isCorrect: null,
    isVisited: false,
  },
  {
    _id: "ds-001",
    question: "Which data structure uses FIFO?",
    options: ["Stack", "Queue", "Tree", "Graph"],
    correctOption: 1,
    difficulty: "easy",
    marks: 1,
    isActive: true,
    userAnswer: null,
    isCorrect: null,
    isVisited: false,
  },
  {
    _id: "js-001",
    question: "Which keyword declares a constant in JavaScript?",
    options: ["var", "let", "const", "static"],
    correctOption: 2,
    difficulty: "easy",
    marks: 1,
    isActive: true,
    userAnswer: null,
    isCorrect: null,
    isVisited: false,
  },
  {
    _id: "net-001",
    question: "What is the default port for HTTP?",
    options: ["21", "80", "443", "3000"],
    correctOption: 1,
    difficulty: "easy",
    marks: 1,
    isActive: true,
    userAnswer: null,
    isCorrect: null,
    isVisited: false,
  },
  {
    _id: "java-001",
    question: "Which company developed Java?",
    options: ["Microsoft", "Oracle", "Sun Microsystems", "Google"],
    correctOption: 2,
    difficulty: "easy",
    marks: 1,
    isActive: true,
    userAnswer: null,
    isCorrect: null,
    isVisited: false,
  },
  {
    _id: "js-002",
    question: "Which symbol is used for comments in JavaScript?",
    options: ["<!-- -->", "//", "#", "**"],
    correctOption: 1,
    difficulty: "easy",
    marks: 1,
    isActive: true,
    userAnswer: null,
    isCorrect: null,
    isVisited: false,
  },
  {
    _id: "lang-001",
    question: "Which of these is NOT a programming language?",
    options: ["Python", "HTML", "Java", "C++"],
    correctOption: 1,
    difficulty: "easy",
    marks: 1,
    isActive: true,
    userAnswer: null,
    isCorrect: null,
    isVisited: false,
  },

  // -------- MEDIUM --------

  {
    _id: "algo-001",
    question: "What is the time complexity of binary search?",
    options: ["O(n)", "O(log n)", "O(n log n)", "O(1)"],
    correctOption: 1,
    difficulty: "medium",
    marks: 2,
    isActive: true,
    userAnswer: null,
    isCorrect: null,
    isVisited: false,
  },
  {
    _id: "net-002",
    question: "Which layer does TCP operate on?",
    options: ["Application", "Transport", "Network", "Physical"],
    correctOption: 1,
    difficulty: "medium",
    marks: 2,
    isActive: true,
    userAnswer: null,
    isCorrect: null,
    isVisited: false,
  },
  {
    _id: "java-002",
    question: "Which Java collection does not allow duplicates?",
    options: ["List", "Map", "Set", "Queue"],
    correctOption: 2,
    difficulty: "medium",
    marks: 2,
    isActive: true,
    userAnswer: null,
    isCorrect: null,
    isVisited: false,
  },
  {
    _id: "api-001",
    question: "What does REST stand for?",
    options: [
      "Reliable State Transfer",
      "Representational State Transfer",
      "Remote State Technique",
      "Response State Transfer",
    ],
    correctOption: 1,
    difficulty: "medium",
    marks: 2,
    isActive: true,
    userAnswer: null,
    isCorrect: null,
    isVisited: false,
  },

  // -------- HARD --------

  {
    _id: "ds-002",
    question: "Which data structure is used in BFS?",
    options: ["Stack", "Queue", "Heap", "Set"],
    correctOption: 1,
    difficulty: "hard",
    marks: 3,
    isActive: true,
    userAnswer: null,
    isCorrect: null,
    isVisited: false,
  },
  {
    _id: "db-001",
    question: "Which SQL command removes all rows but keeps the table?",
    options: ["DELETE", "DROP", "TRUNCATE", "REMOVE"],
    correctOption: 2,
    difficulty: "hard",
    marks: 3,
    isActive: true,
    userAnswer: null,
    isCorrect: null,
    isVisited: false,
  },
  {
    _id: "react-001",
    question: "Which React feature avoids prop drilling?",
    options: ["Hooks", "Context API", "Redux", "Fragments"],
    correctOption: 1,
    difficulty: "hard",
    marks: 3,
    isActive: true,
    userAnswer: null,
    isCorrect: null,
    isVisited: false,
  },
];
